# Generated by Django 2.2.8 on 2024-01-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.UUIDField()),
                ('type', models.CharField(max_length=255)),
                ('severity', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
