# Generated by Django 2.2.8 on 2024-01-19 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_auto_20240119_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='handler.Handler'),
        ),
    ]
